name: playground
description: "Design Kit Playground"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # DesignKit dependency pulled directly from GitHub
  designkit:
     git:
        url: https://github.com/Assam-Internship-2025-2026-BS6/Flutter-DesignKit-.git
        ref: develop
        path: designkit


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
